# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test: 

    docker:
      # specify the version you desire here
      - image: cypress/base:10
    working_directory: ~/repo
      steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-

        - run: yarn install


        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        # run build!
        - run: yarn build

        # run test!
        - run: yarn test

      
  build:

    docker:
      # specify the version you desire here
      - image: cypress/node:11.6.0

      # PostgreSql
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: manuelruck
          POSTGRES_DB: myproject

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install


      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run build!
      - run: yarn build

      # run lint!
      - run: yarn lint

      # run test!
      - run: yarn test